"""Initial migration

Revision ID: 078f13474c81
Revises: 
Create Date: 2026-03-17 23:44:36.197585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078f13474c81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notes', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notes', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.drop_constraint(op.f('notes_video_id_fkey'), 'notes', type_='foreignkey')
    op.drop_constraint(op.f('notes_owner_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('videos', 'club_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.drop_constraint(op.f('videos_owner_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_owner_id_fkey'), 'videos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.alter_column('videos', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos', 'club_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_owner_id_fkey'), 'notes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notes_video_id_fkey'), 'notes', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.alter_column('notes', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notes', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notes', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
